#+TITLE: Oracle 11g for OEM 
* Overview
Use vagrant to provision and provide oracle 11g for oem
* Dependencies
Assumes Vagrant & Virtualbox are available, and the =ol6minimal= Vagrant box is available.

=ol6minimal= can be obtained from MY GITHUP PROJECT
* Setup
Download database zip files from Oracle into the current directory. 

The database is 11.2.0.3.0, downloadable as patch 10404530 from My Oracle Support. You must have an Oracle license to download and use the database.

The database template zip file is at http://www.oracle.com/technetwork/oem/enterprise-manager/downloads/db-templates-1959276.html

Files needed and links are:
| file                                                    | Description                      |
|---------------------------------------------------------+----------------------------------|
| p10404530_112030_Linux-x86-64_1of7.zip                  | 11g db install                   |
| p10404530_112030_Linux-x86-64_2of7.zip                  | 11g db install                   |
| 11.2.0.3_Database_Template_for_EM12_1_0_4_Linux_x64.zip | Templates for Enterprise Manager |
Database zip files are in current directory (you can unzip the database files if you wish, or the provisioning process will do it for you)
* Operation
Super Simple (thanks to Vagrant!)
Initialize the VM and it will provision itself (look inside =setup.sh= to see what's going on)
#+BEGIN_SRC sh
vagrant up
#+END_SRC
If that succeeds you should have an updated VM with Oracle 11g available on port localhost:11521.
